-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE events (
    id SERIAL PRIMARY KEY,
    name text,
    date date
);

-- Indices -------------------------------------------------------

--CREATE UNIQUE INDEX events_pkey ON events(id int4_ops);

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name text
);

-- Indices -------------------------------------------------------

--CREATE UNIQUE INDEX users_pkey ON users(id int4_ops);

-- RETURNING is optional & shows what its entry looks like in the table when inserted
INSERT INTO public.events(name, date) VALUES('Vegan Sushi Night', '2022-03-03') RETURNING id, name, date;
INSERT INTO public.events(name, date) VALUES('Anniversary Tea Party', '2021-08-31') RETURNING id, name, date;
INSERT INTO public.events(name, date) VALUES('Pumpkin Patch', '2021-10-13') RETURNING id, name, date;
INSERT INTO public.events(name, date) VALUES('House Warming', '2021-04-04') RETURNING id, name, date;

INSERT INTO public.users(name) VALUES('picaq') RETURNING id, name;
INSERT INTO public.users(name) VALUES('sunnybrie') RETURNING id, name;
INSERT INTO public.users(name) VALUES('teddybear') RETURNING id, name;
INSERT INTO public.users(name) VALUES('carbonsoda') RETURNING id, name;

-- update events set date = '2022-03-03' where id = 1;